_target_: glm_experiments.models.lm_lit_module.SimCSELitModule

soft_masked_weight: ${data.soft_masked_weight}
evals: ${data.evals}

net:
  _target_: glm_experiments.models.components.lm.SimCSE
  embedder:
    _target_: glm_experiments.models.components.transformer.Embedding
    vocab_size: 7
    d_model: 128
  encoder:
    _target_: glm_experiments.models.components.cnn_pyramid.ConvPyramid
    d_model: ${..embedder.d_model}
    n_stages: 9
    channel_growth: 16
    kernel_size: 5
    initial_kernel_size: 15
    dropout: 0.1
  layer_norm:
    _target_: torch.nn.RMSNorm
    normalized_shape: ${..embedder.d_model}
  dropout_p: 0.1
  temperature: 0.05

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.1
  betas: [0.9, 0.98]
  eps: 1.0e-9

scheduler:
  _target_: transformers.get_constant_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 500
